trigger:
- none

parameters:
- name: VM_Environment_Name
  displayName: 'VM Environment Name'
  type: string
  values:
  - TEST1
  - TEST2
  - TEST3
  default: TEST1
- name: Destination_Machine_Name
  displayName: 'Destination Machine Name'
  type: string
  values:
  - DENBG0817VM
  - DENBG0811VM
  default: DENBG0817VM

variables:
  dcusername: 'dcadmin'
  dcpassword: 'dcadmin'
  DC_QUICK_DEPLOY_PATH: '/opt/app/siemens/dc_14.1/deployment_center/additional_tools/internal/dc_quick_deploy'
  DC_URL: 'http://192.168.80.54:8080/deploymentcenter'
  DC_DEPLOY_SCRIPT_DIR_NAME: 'deploy'
  JAVA_HOME: '/opt/app/siemens/JAVA/jdk-11.0.21'
  TARGET_VM_DEPLOY_SCRIPTS_DIR: '/opt/app/siemens'
  TARGET_VM_MAPPED_DRIVE_BACK_TO_DC_REPO: '/opt/app/siemens/dc_14.1/repository/deploy_scripts'
  #TARGET_VM_SOFTWARE_LOCATION: '/opt/app/siemens/dc_14.1/repository/software'  # SoftwareLocation
  TARGET_VM_SOFTWARE_LOCATION: '/mnt/dumps/TC/TC14' 
  INPUT_FILE_PATH: '/opt/app/siemens/Sample_xml_Files/LS24_install_Fnd140.xml'
  BUILD_NO: $(Build.BuildNumber)
  BUILD_NUMBER: ${BUILD_NO//./_}
  SCRIPTS_DIR_NAME: $(DC_DEPLOY_SCRIPT_DIR_NAME)_$(BUILD_NUMBER)
  DC_ENV_NAME: ${{ parameters.VM_Environment_Name }}_$(BUILD_NUMBER)


stages:
- stage: Prepare
  jobs:
  - job: Prepare_Azure_Variables
    pool:
      name: TC_811
    steps:
    - script: |
        # Setting the specified variables
        
        target_vm_machine_name='${{ parameters.Destination_Machine_Name }}' 
        dcEnvironmentName='${{ parameters.VM_Environment_Name }}_$(Build.BuildNumber)'
        machine_script_dir_name='deploy_'$target_vm_machine_name
        machine_script_zip_name=$machine_script_dir_name.zip
        scripts_dir_name='$(DC_DEPLOY_SCRIPT_DIR_NAME)_$(Build.BuildNumber)'
        machine_script_path=$(TARGET_VM_MAPPED_DRIVE_BACK_TO_DC_REPO)/$dcEnvironmentName/install/$scripts_dir_name/$machine_script_zip_name
        unzip_target_path=$(TARGET_VM_DEPLOY_SCRIPTS_DIR)/$scripts_dir_name/$machine_script_dir_name
        
      displayName: 'Prepare Azure Variables'

- stage: Generate_Deploy_Script
  jobs:
  - job: Generate
    pool:
      name: TC_811
    steps:
    - script: |
        TARGET_VM_MACHINE_NAME='${{ parameters.Destination_Machine_Name }}'
        DC_ENV_NAME=${{ parameters.VM_Environment_Name }}_$(BUILD_NUMBER)
        echo "Generating Deploy script using Quick Deploy"
        cd $(DC_QUICK_DEPLOY_PATH) && ./dc_quick_deploy.sh -dcurl=$(DC_URL) -environment=$DC_ENV_NAME -inputFile=$(INPUT_FILE_PATH) -dcusername=$(dcusername) -dcpassword=$(dcpassword) -scriptDirectoryName=$(SCRIPTS_DIR_NAME) -machine=$TARGET_VM_MACHINE_NAME
      displayName: 'Generate Deploy Script'
- stage: Copy_Deploy_Script
  jobs:
  - job: Publish_Artifact
    pool:
      name: TC_811 
    
    steps:
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(TARGET_VM_MAPPED_DRIVE_BACK_TO_DC_REPO)/$(DC_ENV_NAME)/install/$(SCRIPTS_DIR_NAME)'
        artifact: 'deploy_scripts'
        publishLocation: 'pipeline'
      displayName: 'Publish Deploy Script Artifact'

- stage: Unzip_Deploy_Script
  jobs:
  - job: Download_And_Unzip
    pool:
      name: TC_817
    steps:
    - download: current
      artifact: deploy_scripts
      displayName: 'Download Deploy Script Artifact'

    - script: |
        echo "Unzipping files on the destination server"
        unzip deploy_${{parameters.Destination_Machine_Name}}.zip -d $(TARGET_VM_DEPLOY_SCRIPTS_DIR)/$(SCRIPTS_DIR_NAME)
      displayName: 'Unzip Files on Destination Server'

- stage: Execute_Deploy_Script
  jobs:
  - job: Execute
    pool:
      name: TC_817
    steps:
    - script: |
        echo "Executing deploy script in the destination server"
        COMMAND="cd $(TARGET_VM_DEPLOY_SCRIPTS_DIR)/$(SCRIPTS_DIR_NAME) && ./deploy.sh -softwareLocation=$(TARGET_VM_SOFTWARE_LOCATION) -dcusername=$(dcusername) -dcpassword=$(dcpassword)"
        ROOT_PASSWORD=$(ROOT_PASSWORD_817)
        REMOTE_COMMAND="echo $ROOT_PASSWORD | sudo -S su - root -c '$COMMAND'"
        echo "Executing command as root: $COMMAND"
        eval "$REMOTE_COMMAND"
      displayName: 'Execute Deploy Script in Destination Server'
