trigger:
- none

pool: 
  name: TC_811

parameters:
- name: VM_Environment_Name
  displayName: 'VM Environment Name'
  type: string
  values:
  - TEST1
  - TEST2
  - TEST3
  default: TEST1
- name: Destination_Machine_Name
  displayName: 'Destination Machine Name'
  type: string
  values:
  - DENBG0817VM
  - DENBG0811VM
  default: DENBG0817VM

variables:
  dcusername: 'dcadmin'
  dcpassword: 'dcadmin'
  DC_QUICK_DEPLOY_PATH: '/opt/app/siemens/dc_14.1/deployment_center/additional_tools/internal/dc_quick_deploy'
  DC_URL: 'http://192.168.80.54:8080/deploymentcenter'
  DC_DEPLOY_SCRIPT_DIR_NAME: 'deploy'
  JAVA_HOME: '/opt/app/siemens/JAVA/jdk-11.0.21'
  TARGET_VM_DEPLOY_SCRIPTS_DIR: '/opt/app/siemens'
  TARGET_VM_MAPPED_DRIVE_BACK_TO_DC_REPO: '/opt/app/siemens/dc_14.1/repository/deploy_scripts'
  TARGET_VM_SOFTWARE_LOCATION: '/mnt/dumps/TC/TC14'
  INPUT_FILE_PATH: '/opt/app/siemens/Sample_xml_Files/test_install_Fnd140.xml'

stages:
- stage: Set_Variables
  jobs:
  - job: Set_Environment_Variables
    pool:
      name: TC_811
    steps:
    - script: |
        #!/bin/bash
        BUILD_NUMBER_TRANSFORMED=$(echo $(Build.BuildNumber) | sed 's/\./_/g')
        DC_ENV_NAME="${{ parameters.VM_Environment_Name }}_${BUILD_NUMBER_TRANSFORMED}"
        SCRIPTS_DIR_NAME="${{ variables.DC_DEPLOY_SCRIPT_DIR_NAME }}_${BUILD_NUMBER_TRANSFORMED}"
        MACHINE_SCRIPT_DIR_NAME="deploy_${{ parameters.Destination_Machine_Name }}"
        MACHINE_SCRIPT_ZIP_NAME="${MACHINE_SCRIPT_DIR_NAME}.zip"
        MACHINE_SCRIPT_PATH="${{ variables.TARGET_VM_MAPPED_DRIVE_BACK_TO_DC_REPO }}/${DC_ENV_NAME}/${SCRIPTS_DIR_NAME}/${MACHINE_SCRIPT_ZIP_NAME}"
        UNZIP_TARGET_PATH="${{ variables.TARGET_VM_DEPLOY_SCRIPTS_DIR }}/${SCRIPTS_DIR_NAME}/${MACHINE_SCRIPT_DIR_NAME}"

        echo "##vso[task.setvariable variable=BUILD_NUMBER_TRANSFORMED]$BUILD_NUMBER_TRANSFORMED"
        echo "##vso[task.setvariable variable=DC_ENV_NAME]$DC_ENV_NAME"
        echo "##vso[task.setvariable variable=SCRIPTS_DIR_NAME]$SCRIPTS_DIR_NAME"
        echo "##vso[task.setvariable variable=MACHINE_SCRIPT_DIR_NAME]$MACHINE_SCRIPT_DIR_NAME"
        echo "##vso[task.setvariable variable=MACHINE_SCRIPT_ZIP_NAME]$MACHINE_SCRIPT_ZIP_NAME"
        echo "##vso[task.setvariable variable=MACHINE_SCRIPT_PATH]$MACHINE_SCRIPT_PATH"
        echo "##vso[task.setvariable variable=UNZIP_TARGET_PATH]$UNZIP_TARGET_PATH"
      displayName: 'Set Environment Variables'

- stage: Generate_Deploy_Script
  jobs:
  - job: Generate
    pool:
      name: TC_811
    steps:
    - script: |
        echo "Generating Deploy script using Quick Deploy"
        cd ${{ variables.DC_QUICK_DEPLOY_PATH }}
        ./dc_quick_deploy.sh -dcurl=${{ variables.DC_URL }} -environment=${{ variables.DC_ENV_NAME }} -inputFile=${{ variables.INPUT_FILE_PATH }} -dcusername=${{ variables.dcusername }} -dcpassword=${{ variables.dcpassword }} -scriptDirectoryName=${{ variables.SCRIPTS_DIR_NAME }} -machine=${{ parameters.Destination_Machine_Name }}
      displayName: 'Generate Deploy Script'

- stage: Copy_Deploy_Script
  jobs:
  - job: Copy
    pool:
      name: TC_811
    steps:
    - script: |
        echo "Copying files to the destination server"
        scp -r ${{ variables.MACHINE_SCRIPT_PATH }} infodba@192.168.80.108:${{ variables.TARGET_VM_DEPLOY_SCRIPTS_DIR }}
      displayName: 'Copy Files to Destination Server'

- stage: Unzip_Deploy_Script
  jobs:
  - job: Unzip
    pool:
      name: TC_811
    steps:
    - script: |
        echo "Unzipping files on the destination server"
        ssh -T -o StrictHostKeyChecking=no infodba@192.168.80.108 unzip ${{ variables.UNZIP_TARGET_PATH }} -d ${{ variables.UNZIP_TARGET_PATH }}
      displayName: 'Unzip Files on Destination Server'

- stage: Execute_Deploy_Script
  jobs:
  - job: Execute
    pool:
      name: TC_811
    steps:
    - script: |
        echo "Executing deploy script on the destination server"
        FULL_COMMAND="cd ${{ variables.UNZIP_TARGET_PATH }} && ./deploy.sh -softwareLocation=${{ variables.TARGET_VM_SOFTWARE_LOCATION }} -dcusername=${{ variables.dcusername }} -dcpassword=${{ variables.dcpassword }}"
        echo "Executing command: $FULL_COMMAND"
        ssh -T -o StrictHostKeyChecking=no infodba@192.168.80.108 "$FULL_COMMAND"
      displayName: 'Execute deploy script on Destination Server'
