trigger:
- none

parameters: 
- name: Destination_Machine_Name
  displayName: 'Destination Machine Name'
  type: string
  default: DENBG0817VM
  values:
  - DENBG0817VM
  - DENBG0000VM
  

variables:
  dcusername: 'dcadmin'
  dcpassword: 'dcadmin'
  DC_QUICK_DEPLOY_PATH: '/opt/app/siemens/dc_14.1/deployment_center/additional_tools/internal/dc_quick_deploy'
  DC_URL: 'http://192.168.80.54:8080/deploymentcenter'
  DC_DEPLOY_SCRIPT_DIR_NAME: 'deploy'
  JAVA_HOME: '/opt/app/siemens/JAVA/jdk-11.0.21'
  TARGET_VM_DEPLOY_SCRIPTS_DIR: '/opt/app/siemens'
  TARGET_VM_MAPPED_DRIVE_BACK_TO_DC_REPO: '/opt/app/siemens/dc_14.1/repository/deploy_scripts'
  TARGET_VM_SOFTWARE_LOCATION: '/opt/app/siemens/dc_14.1/repository/software'  
  #TARGET_VM_SOFTWARE_LOCATION: '/mnt/dumps/TC/TC14' 
  INPUT_FILE_PATH: '/opt/app/siemens/Sample_xml_Files//Working/Install_Fnd140.xml'
  BUILD_NO: $(Build.BuildNumber)
  BUILD_NUMBER: ${BUILD_NO//./_}
  SCRIPTS_DIR_NAME: $(DC_DEPLOY_SCRIPT_DIR_NAME)_$(BUILD_NUMBER)
  DC_ENV_NAME: ENV_${{ parameters.Destination_Machine_Name }}_$(BUILD_NUMBER)
  SOURCE_PATH_ARTIFACT: $(TARGET_VM_MAPPED_DRIVE_BACK_TO_DC_REPO)/$(DC_ENV_NAME)/install


stages:
- stage: Prepare
  jobs:
  - job: Prepare_Azure_Variables
    pool:
      name: TC_811
    steps:
    - script: |
        # Setting the specified variables
        target_vm_machine_name='${{ parameters.Destination_Machine_Name }}' 
        dcEnvironmentName='ENV_${{ parameters.Destination_Machine_Name }}_$(Build.BuildNumber)'
        machine_script_dir_name='deploy_'$target_vm_machine_name
        machine_script_zip_name=$machine_script_dir_name.zip
        scripts_dir_name='$(DC_DEPLOY_SCRIPT_DIR_NAME)_$(Build.BuildNumber)'
        machine_script_path=$(TARGET_VM_MAPPED_DRIVE_BACK_TO_DC_REPO)/$dcEnvironmentName/install/$scripts_dir_name/$machine_script_zip_name
        unzip_target_path=$(TARGET_VM_DEPLOY_SCRIPTS_DIR)/$scripts_dir_name/$machine_script_dir_name

      displayName: 'Prepare Azure Variables'

- stage: Generate_Deploy_Script
  jobs:
  - job: Generate_Deploy_Script
    pool:
      name: TC_811
    steps:
    - script: |
        TARGET_VM_MACHINE_NAME='${{ parameters.Destination_Machine_Name }}'
        DC_ENV_NAME=ENV_${{ parameters.Destination_Machine_Name }}_$(BUILD_NUMBER)
        echo "Generating Deploy script using Quick Deploy"
        cd $(DC_QUICK_DEPLOY_PATH) && ./dc_quick_deploy.sh -dcurl=$(DC_URL) -environment=$DC_ENV_NAME -inputFile=$(INPUT_FILE_PATH) -dcusername=$(dcusername) -dcpassword=$(dcpassword) -scriptDirectoryName=$(SCRIPTS_DIR_NAME) -machine=$TARGET_VM_MACHINE_NAME
      
      displayName: 'Generate Deploy Script'

- stage: Publish_Artifact
  jobs:
  - job: Publish_Artifact
    pool:
      name: TC_811   
    steps:
    - script: |
        echo "##vso[task.setvariable variable=SOURCE_PATH_ARTIFACT]$(SOURCE_PATH_ARTIFACT)"

      displayName: 'Set Variables for Publishing'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(SOURCE_PATH_ARTIFACT)'
        artifact: 'deploy_scripts'
        publishLocation: 'pipeline'

      displayName: 'Publish Deploy Script Artifact'

- stage: Download_artifact
  jobs:
  - job: Download_artifact
    pool:
      name: TC_817
    steps:
    - script: |
        echo "##vso[task.setvariable variable=TARGET_VM_DEPLOY_SCRIPTS_DIR]$(TARGET_VM_DEPLOY_SCRIPTS_DIR)"
      
      displayName: 'Set Variables for Publishing'
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'deploy_scripts'
        targetPath: '$(TARGET_VM_DEPLOY_SCRIPTS_DIR)'

      displayName: 'Download Deploy Script Artifact'


- stage: Unzip_Deploy_Script
  jobs:
  - job: Unzip_Deploy_Script
    pool:
      name: TC_817
    steps:
    - script: |
        echo "Unzipping files on the destination server"
        TARGET_VM_MACHINE_NAME='${{ parameters.Destination_Machine_Name }}'
        MACHINE_SCRIPT_DIR_NAME='deploy_'$TARGET_VM_MACHINE_NAME
        MACHINE_SCRIPT_ZIP_NAME=$MACHINE_SCRIPT_DIR_NAME.zip
        unzip $(TARGET_VM_DEPLOY_SCRIPTS_DIR)/$(SCRIPTS_DIR_NAME)/$MACHINE_SCRIPT_ZIP_NAME -d $(TARGET_VM_DEPLOY_SCRIPTS_DIR)/$(SCRIPTS_DIR_NAME)/$MACHINE_SCRIPT_DIR_NAME
        
      displayName: 'Unzip Files on Destination Server'

- stage: Execute_Deploy_Script
  jobs:
  - job: Execute
    pool:
      name: TC_817
    steps:
    - script: |
        echo "Executing deploy script in the destination server"
        TARGET_VM_MACHINE_NAME='${{ parameters.Destination_Machine_Name }}'
        MACHINE_SCRIPT_DIR_NAME='deploy_'$TARGET_VM_MACHINE_NAME
        COMMAND="cd $(TARGET_VM_DEPLOY_SCRIPTS_DIR)/$(SCRIPTS_DIR_NAME)/$MACHINE_SCRIPT_DIR_NAME && ./deploy.sh -softwareLocation=$(TARGET_VM_SOFTWARE_LOCATION) -dcusername=$(dcusername) -dcpassword=$(dcpassword)"
        ROOT_PASSWORD=$(ROOT_PASSWORD_817)
        REMOTE_COMMAND="echo $ROOT_PASSWORD | sudo -S su - root -c '$COMMAND'"
        echo "Executing command as root: $COMMAND"
        eval "$REMOTE_COMMAND"
        
      displayName: 'Execute Deploy Script in Destination Server'
